### ISSUE TITLE
Print commands for ipptransform

### ISSUE THREAD

**Issue by navita1837** [istopwg/ippsample#212]
@michaelrsweet  
Please provide some suggestions to achieve print prn file local printer using command in ippserver.
As i read in ipptransform man page :
 ipptransform is normally run by ippserver(8) to convert document data for printing.

My requirement is to add a command in ippserver.
Using this command i want to print .prn to any printer.

i.e
ippserver is running in Ubuntu 16.04. 
and i have my own text file in Ubuntu. I need to print this file (Job process) to local printer(parallel port) using command.
can we make use of cups library?

**Comment by michaelrsweet** [comment]
@navita1837 It would be helpful to know what you are trying to do, and what kind of printer you are using. Since you are using Ubuntu, the simplest way to support your printer is to use CUPS itself with a printer driver for your printer. ippserver and ipptransform *might* work - you can send print data to an old parallel port using the character device files like /dev/lp0, e.g.:

    cat filename.prn >/dev/lp0

The ipptransform program supports converting some input files (but NOT plain text files) to HP PCL, which will work for any PCL printer. But it won't handle printing plain text files...

**Comment by navita1837** [comment]
@michaelrsweet 
ippserver is running in ubuntu,
I have initiated a text document print from Windows --> ippserver(Ubuntu) and now i have a prn file of that text file.

Now i want to process this job file (.prn print) using ippserver command option to actual printer which is connected to Ubuntu (Printer is not finalized).
