### ISSUE TITLE
Not support color PCL output

### ISSUE THREAD

**Issue by hudongcheng** [istopwg/ippsample#23]
Hi,

I tested to print color image, It seems not support color PCL output.
```
tools/ipptransform -d socket://127.0.0.1:9100/ -m application/vnd.hp-pcl -t srgb_8 -o media=iso_a4_210x297mm examples/testfile.jpg
```
I dump the print file which viewed in PCLWorkx, and found that it was gray.

PWG is OK, and is enough for me.  But maybe still a problem for printer that only support PCL.

Thanks.

**Comment by michaelrsweet** [comment]
The problem with color PCL is that there are literally hundreds of different versions we'd need to support, with no common "basic" color graphics mode like there is for B&W and no way to reliably auto-detect which version we'd need to use.

Since the primary goal of this project is to provide sample implementations of IPP, particularly for modern high-level file formats, coming up with a new way to implement printer drivers is not something we want to do - that already exists in CUPS.
