### ISSUE TITLE
Install all tools to BUILDROOT/bin

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#237]
This project installs some tools to BUILDROOT/bin (by default /usr/local/bin), but others to BUILDROOT/sbin (ippproxy and ippserver) and yet others to BUILDROOT/libexec/cups/command (ipptransform, ipptransform3d, and ippdoclint). Although individuals could add all 3 of these to their PATH, change the installation to install all of these into BUILDROOT/bin.

**Comment by michaelrsweet** [comment]
@wifiprintguy ippserver is generally a system process, so "sbin" is the appropriate location for it.

As for the transform and lint tools, those are used by ippserver and the current code looks for them (and any other "print commands") in that specific location for security reasons.

**Comment by wifiprintguy** [comment]
@michaelrsweet not sure how to comment on the system process or security concerns about the other tools, but I do know that they are much less readily available as developer tools if they are in those locations unless someone starts hunting around BUILDROOT and I thought putting them all in BUILDROOT/bin would help with that.

**Comment by michaelrsweet** [comment]
@wifiprintguy Well, I can understand not easily finding ipptransform but it shouldn't be a stretch to find a server program in PREFIX/sbin.

I would be OK with installing the tools to PREFIX/bin and symlinking them to the LIBEXEC/cups/command directory. It is LIBEXEC/cups/command because ippserver and ipp3dprinter "borrow" the ippeveprinter command interface, and CUPS supplies its own PCL and PostScript printer commands/tools...
