### ISSUE TITLE
How to make ipptransform build (and create a usable binary)?

### ISSUE THREAD

**Issue by attah** [istopwg/ippsample#262]
When i run `./configure && make -j` i don't get a ipptransform binary.

What controls this, and how can i fix it?
From another issue i saw a suggestion of having a recent mupdf installed, so i built and installed version 1.19.1, but that didn't help.
If i go to the tools directory, i can run `make ipptransform`, and it produces the binary.
I did however have to add ctype.h and errno.h includes and do get a warning for xform_setup not being used, so maybe something is off.

If i then go to run the ipptransform binary, it does output help text, but not convert any documents.
It just returns immediately with no message or special exit status.
There was no difference with fudging in the libcups.so.3 with LD_LIBRARY_PATH, or having it actually make-installed (which did not bring ipptransform with it).

I'm on Linux Mint 20.3, i.e. basically Ubuntu 20.04 with latest updates.

**Comment by michaelrsweet** [comment]
@attah The current ipptransform source does not build and is not complete. Reliance on MuPDF was removed due to the APIs changing constantly for no reason and because the license was going to get people in trouble if they actually tried to use it for production use (Apache + AGPL = AGPL) which we obviously do not recommend in any case because ippsample only contains sample code and not a usable “product”.

I hope to complete the ipptransform code in the next few weeks, at which point it will once again build.

**Comment by attah** [comment]
Okay, thanks for info!
I was just going to do some friendly benchmarking with my [application](https://github.com/attah/ppm2pwg#pdf2printable) that does more or less the same thing, so no worries.

So no regular GPL either then i assume? Are you headed to pdftoppm and a pipe in-between, or something like pdfium?
I gave in to GPL, since that is good for what i'm doing anyway.

**Comment by michaelrsweet** [comment]
@attah For now pdftoppm (from poppler or xpdf) for rasterizing PDF files, and PDFio to filter them. I’d love to try pdfium but it’s build system is insane and there is no way we could rely on/support it.
