### ISSUE TITLE
ippproxy error

### ISSUE THREAD

**Issue by sheenvempeny** [istopwg/ippsample#78]
I am new to ipp. I added a printer to my system (no network, only local) using lpadmin. I run the ippserver code with that printer name. I tried to connect it with ippproxy. I am getting this error "The printer or class does not exist."

This is the command I tried,
ipproxy ipp://sheens-MacBook-Pro.local:631/VirtualPrinter -d dnssd://VirtualPrinter._ipp._tcp.local./?uuid=bd1bd1a1-82cc-480d-86e9-c8325d352246
ippproxy: UUID for 'dnssd://VirtualPrinter._ipp._tcp.local./?uuid=bd1bd1a1-82cc-480d-86e9-c8325d352246' is 'urn:uuid:00000000-0000-3000-7fff-00000000000'.
ippproxy: Unable to monitor events on 'ipp://sheens-MacBook-Pro.local:631/VirtualPrinter': The printer or class does not exist.

**Comment by michaelrsweet** [comment]
The ippproxy implementation in the sample code repository is not yet complete.

**Comment by sheenvempeny** [comment]
Is it possible ippserver can accept printing job from other app without a ippproxy client ?. 
When I did the print operation from Safari to the printer ( ippserver running), it is showing, "Looking for printer".

**Comment by michaelrsweet** [comment]
Yes, ippserver can absolutely handle that - ippproxy is only needed when you are crossing network firewalls.

**Comment by sheenvempeny** [comment]
Thank you for the response. May I know, why the printer service "Looking for Printer" even the ippserver is running ?.

**Comment by michaelrsweet** [comment]
Probably the UUID has changed between runs - that will prevent CUPS from finding a matching printer. You can modify the printer and remove the uuid=... part of the CUPS device URI to avoid this problem.

(but generally speaking since you are using a Mac you have CUPS and there is no need to be running ippserver except for simulating printers, and even then the Printer Simulator application included with the Xcode hardware tools add-on is a lot easier to use.

**Comment by sheenvempeny** [comment]
Yes, you are correct. That was the issue. Thanks a lot.
I will look on the Printer Simulator app.
